---
stages:
  - build


image: registry.gitlab.com/modioab/base-image/fedora-31/container:master

before_script:
  - make -f build.mk login
  - podman info


zabbixui:build:
    stage: build
    except:
        - pushes
    script:
        - make -C zabbixui build-publish

mongodb:
  stage: build
    except:
        - pushes
  script:
    - make -C mongodb build-publish


caramel:
  stage: build
  except:
    - pushes
  script:
    - make -C caramel build-publish
