---
stages:
  - build
  - publish

image: registry.gitlab.com/modioab/base-image/fedora-31/container:master

before_script:
  - make -f build.mk login
  - podman info


zabbixui:build:
    stage: build
    except:
        - pushes
    script:
        - make -C zabbixui build-publish

mongodb:
  stage: build
    except:
        - pushes
  script:
    - make -C mongodb build-publish

container:
    image: registry.gitlab.com/modioab/base-image/fedora-31/container:master
    stage: publish
    tags:
        - x86_64
    script:
        - make -f build.mk login
        - make build-publish
        - make -C tool build-publish
