---
stages:
  - build
  - second


image: registry.gitlab.com/modioab/base-image/fedora-31/container:master

before_script:
  - make -f build.mk login
  - podman info


zabbixui:
  stage: build
  script:
    - make -C zabbixui build-publish


mongodb:
  stage: build
  script:
    - make -C mongodb build-publish


caramel:
  stage: build
  script:
    - make -C caramel build-publish


caramel:tool:
  stage: second
  needs:
    - caramel
  script:
    - IMAGE_TAG_SUFFIX=${CI_COMMIT_REF_NAME/master/latest} make -C caramel_tool build-publish
