# vim: expandtab:ts=8:sw=2:tw=80:fdm=marker:ft=yaml:
%YAML 1.1
---
# Keep the includes first to illustrate that definitions that everything that
# follows override included definitions.
include:
  # Use MergeRequest pipelines
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: ModioAB/CI
    ref: main
    file:
      - /ci/default.yml
      - /ci/container.yml

stages:
  - build
  - second
  - test
  - deploy

.matrix:
  parallel:
    matrix:
      - SUBDIR:
          - caramel
          - caramel-sqlite
        IMAGE_BUILD_FROM: ${PYTHON_IMAGE}
      - SUBDIR:
          - zabbixui
          - zabbix-server
          - mongodb
          - debos
          - bacula/client
          - bacula/console
          - bacula/director
          - bacula/storage

build:
  extends:
    - .container:build
    - .matrix

container:publish:
  extends:
    - .container:publish
    - .matrix

# caramel_tool needs the previous "caramel" image. Thus it's split.
caramel_tool:build:
  extends: .container:build
  stage: second
  needs:
    - build
  variables:
    SUBDIR: caramel_tool
    IMAGE_BUILD_FROM: ${CI_REGISTRY_IMAGE}/caramel:${CI_PIPELINE_ID}

caramel_tool:publish:
  extends: .container:publish
  needs:
    - caramel_tool:build
  variables:
    SUBDIR: caramel_tool
...
