IMAGE_REPO = registry.gitlab.com/modioab/containers/bacula/storage

FEDORA_ROOT_ARCHIVE = rootfs.tar
IMAGE_FILES += $(FEDORA_ROOT_ARCHIVE)

FEDORA_ROOT_PACKAGES += bacula-storage

include ../../build.mk
