IMAGE_REPO = registry.gitlab.com/modioab/containers/bacula/director

FEDORA_ROOT_ARCHIVE = rootfs.tar
IMAGE_FILES += $(FEDORA_ROOT_ARCHIVE)

FEDORA_ROOT_PACKAGES += bacula-director

include ../../build.mk
